app:
  file-security:
    storage-root: /opt/app/files
    max-upload-size-bytes: 10485760

    allowed-content-types:
      - image/jpeg
      - image/png
      - image/webp
      - application/pdf

    caller-policies:
      - caller: "fidelity25.it"
        roots:
          - "twentyfive-fidelity"

      - caller: "80.211.123.141:8104"
        roots:
          - "apa"

      - caller: "80.211.123.141:8106"
        roots:
          - "buste-paga"
logging:
  level:
    root: INFO
    com.example.twentyfivemediamanager: DEBUG
    org.springframework.security: INFO